# Generated by Django 6.1.1 on 2026-10-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name, e.g. Work, Personal', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional brief description')),
                ('color', models.CharField(choices=[('indigo', 'Indigo (#6366F1)'), ('blue', 'Blue (#3B82F6)'), ('emerald', 'Emerald (#10B981)'), ('amber', 'Amber (#F59E0B)'), ('rose', 'Rose (#F43F5E)'), ('purple', 'Purple (#A855F7)'), ('cyan', 'Cyan (#06B6D4)'), ('gray', 'Slate (#64748B)')], default='indigo', max_length=20)),
                ('icon', models.CharField(choices=[('briefcase', 'Briefcase (Work)'), ('user', 'User (Personal)'), ('academic-cap', 'Graduation Cap (Study/Learning)'), ('currency-dollar', 'Currency (Finance)'), ('heart', 'Heart (Health & Fitness)'), ('code', 'Code (Development)'), ('sparkles', 'Sparkles (Ideas)'), ('folder', 'Folder (General)')], default='folder', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Note headline', max_length=200)),
                ('content', models.TextField(help_text='Body content or bullet points')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of the dashboard and notes list')),
                ('theme', models.CharField(choices=[('yellow', 'Warm Amber'), ('blue', 'Sky Blue'), ('emerald', 'Emerald Mint'), ('purple', 'Purple Lavender'), ('rose', 'Rose Bloom'), ('slate', 'Modern Slate')], default='yellow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='tasks.category')),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Clear title of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed notes or checklists')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=15)),
                ('due_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0.0, help_text='Estimated time in hours (e.g. 1.5)', max_digits=5)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.category')),
            ],
            options={
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
    ]
